### PR TITLE
Run rustfmt

### PR DESCRIPTION
**Pull request by steveklabnik**
@nrc has built a great tool for formatting, and it worked pretty well
here!

### CODE REVIEW

**Comment by steveklabnik** [comment]
There are some other small, non-formatting idiom stuff I noticed. Do you want a PR for those?

**Comment by NicolasLM** [comment]
I'm gonna check rustfmt in the future. I just merged a few things, would you mind re-running it on master?
About other improvements, yes sure it would be great!

**Comment by steveklabnik** [comment]
Done!

> yes sure it would be great!

Roger that!

**Comment by steveklabnik** [comment]
Updated with master.

**Comment by NicolasLM** [comment]
Thanks!

**Pull request merged**
